package resonantinduction.archaic;

import java.util.Arrays;
import java.util.logging.Logger;

import resonantinduction.Reference;
import resonantinduction.core.ResonantInduction;
import calclavia.lib.utility.LanguageUtility;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;

@Mod(modid = ArchaicTier.ID, name = Reference.NAME + " Archaic Tier", version = Reference.VERSION, dependencies = "required-after:" + ResonantInduction.ID)
public class ArchaicTier
{
    /** Mod Information */
    public static final String ID = "ResonantInduction|Archaic";

    @Instance(ID)
    public static ResonantInduction INSTANCE;

    @SidedProxy(clientSide = "resonantinduction.archaic.ArcClientProxy", serverSide = "resonantinduction.archaic.ArcCommonProxy")
    public static ArcCommonProxy proxy;

    @Mod.Metadata(ID)
    public static ModMetadata metadata;

    public static final Logger LOGGER = Logger.getLogger(Reference.NAME);

    @EventHandler
    public void preInit(FMLPreInitializationEvent evt)
    {
        NetworkRegistry.instance().registerGuiHandler(this, proxy);
    }

    @EventHandler
    public void init(FMLInitializationEvent evt)
    {
        metadata.modId = ID;
        metadata.name = Reference.NAME + " Archaic Tier";
        metadata.description = LanguageUtility.getLocal("meta.resonantinduction.archaic.description");
        metadata.url = "http://calclavia.com/resonant-induction";
        metadata.logoFile = "ri_logo.png";
        metadata.version = Reference.VERSION + "." + Reference.BUILD_VERSION;
        metadata.authorList = Arrays.asList(new String[] { "Calclavia", "DarkCow" });
        metadata.credits = LanguageUtility.getLocal("meta.resonantinduction.credits");
        metadata.autogenerated = false;
    }
}
